# Generated by Django 5.2.15 on 2026-07-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Từ khoá tìm kiếm')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ kết quả')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người tìm kiếm')),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('accuracy', models.FloatField(verbose_name='Độ chính xác (mét)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Vận tốc (m/s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử GPS',
                'verbose_name_plural': 'Lịch sử GPS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='history_gps_user_id_c99083_idx')],
            },
        ),
    ]
