# Generated by Django 5.2.15 on 2026-07-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(max_length=255, verbose_name='Điểm xuất phát')),
                ('end_name', models.CharField(max_length=255, verbose_name='Điểm đến')),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ xuất phát')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ xuất phát')),
                ('end_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ đích')),
                ('end_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ đích')),
                ('distance', models.FloatField(verbose_name='Tổng khoảng cách (m)')),
                ('duration', models.FloatField(verbose_name='Tổng thời gian (s)')),
                ('algorithm', models.CharField(choices=[('dijkstra', 'Dijkstra'), ('a_star', 'A* (A-Star)')], default='dijkstra', max_length=20, verbose_name='Thuật toán')),
                ('geometry', models.JSONField(blank=True, default=list, verbose_name='Danh sách toạ độ vẽ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tuyến đường lưu trữ',
                'verbose_name_plural': 'Tuyến đường lưu trữ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('sequence', models.PositiveIntegerField(verbose_name='Thứ tự điểm')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='routes.route', verbose_name='Tuyến đường')),
            ],
            options={
                'verbose_name': 'Điểm trên tuyến',
                'verbose_name_plural': 'Các điểm trên tuyến',
                'ordering': ['sequence'],
            },
        ),
    ]
