# Generated by Django 5.2.15 on 2026-07-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề báo cáo')),
                ('participants_count', models.IntegerField(default=30, verbose_name='Số người tham gia thử nghiệm (UAT)')),
                ('completion_rate', models.FloatField(default=95.0, verbose_name='Tỷ lệ hoàn thành tác vụ (%)')),
                ('satisfaction_rate', models.FloatField(default=93.0, verbose_name='Tỷ lệ hài lòng (%)')),
                ('avg_gps_error', models.FloatField(default=4.2, verbose_name='Sai số GPS trung bình (mét)')),
                ('avg_api_response_ms', models.FloatField(default=120.0, verbose_name='Phản hồi API trung bình (ms)')),
                ('routing_success_rate', models.FloatField(default=98.5, verbose_name='Tỷ lệ tìm đường thành công (%)')),
                ('avg_page_load_seconds', models.FloatField(default=1.1, verbose_name='Thời gian tải trang trung bình (s)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Chi tiết & Phân tích')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Báo cáo thử nghiệm (UAT)',
                'verbose_name_plural': 'Báo cáo thử nghiệm (UAT)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Đánh giá (1-5 sao)')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ý kiến phản hồi',
                'verbose_name_plural': 'Ý kiến phản hồi',
                'ordering': ['-created_at'],
            },
        ),
    ]
