# Generated by Django 5.2.15 on 2026-07-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fa-location-dot', max_length=50, verbose_name='Icon FontAwesome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Danh mục địa điểm',
                'verbose_name_plural': 'Danh mục địa điểm',
            },
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nút (nếu có)')),
            ],
            options={
                'verbose_name': 'Nút đồ thị',
                'verbose_name_plural': 'Các nút đồ thị',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='locations_r_latitud_d66722_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên địa điểm')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx'), models.Index(fields=['category'], name='locations_l_categor_860b47_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Khoảng cách (mét)')),
                ('points', models.JSONField(blank=True, default=list, verbose_name='Đoạn đường chi tiết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='locations.routenode', verbose_name='Nút xuất phát')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='locations.routenode', verbose_name='Nút đích')),
            ],
            options={
                'verbose_name': 'Cạnh đồ thị',
                'verbose_name_plural': 'Các cạnh đồ thị',
                'unique_together': {('node_a', 'node_b')},
            },
        ),
    ]
