# Generated by Django 5.2.15 on 2026-07-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx')],
            },
        ),
    ]
